### ISSUE TITLE
Support special tags like "user:opai" or "vote:3:opai order:vote"

### ISSUE THREAD

**Issue by xeron** [xeron/danbooru-ruby-grabber#10]
Currently it results in (at least on Windows):
```
C:\Users\Henry\Downloads\danbooru-ruby-grabber-master\danbooru-ruby-grabber-master>danbooru.rb -b konachan user:opai
Tags are user:opai.
C:/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:253:in `mkdir': Not a directory @ dir_s_mkdir - user:opai (Errno::ENOTDIR)
        from C:/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:253:in `fu_mkdir'
        from C:/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:227:in `block (2 levels) in mkdir_p'
        from C:/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:225:in `reverse_each'
        from C:/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:225:in `block in mkdir_p'
        from C:/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:211:in `each'
        from C:/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
        from C:/Users/Henry/Downloads/danbooru-ruby-grabber-master/danbooru-ruby-grabber-master/lib/booru/posts.rb:42:in `download_by_tags'
        from C:/Users/Henry/Downloads/danbooru-ruby-grabber-master/danbooru-ruby-grabber-master/danbooru.rb:106:in `<main>'
```

**Comment by xeron** [comment]
Works on Mac. So the issue is a directory name.
